GET http://localhost:3001/api/persons/2
###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Juan Real Madrid",
    "number": "014-0000088"
}
###
PUT http://localhost:3001/api/persons/676ee2c33ed0a36d685a8fe4
Content-Type: application/json

{
    "name": "Juan Real Madrid",
    "number": "014-881932"
}
###
DELETE http://localhost:3001/api/persons/676ee2c33ed0a36d685a8fe4